import React, { createContext, useState, ReactNode, useCallback } from 'react';

type Language = 'ru' | 'en';

interface LocalizationContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

export const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ru: {
    dashboard: 'Панель управления',
    tenders: 'Тендеры',
    client_requests: 'Заявки клиентов',
    clients: 'Клиенты',
    suppliers: 'Поставщики',
    finances: 'Финансы',
    agents: 'Агенты',
    employees: 'Сотрудники',
    approvals: 'Согласования',
    audit_log: 'Журнал аудита',
    settings: 'Настройки',
    Admin: 'Администратор',
    Manager: 'Менеджер',
    Analyst: 'Аналитик',
    Developer: 'Разработчик',
    Client: 'Клиент',
    active_requests: 'Активные заявки',
    active_clients: 'Активные клиенты',
    new_requests: 'Новые заявки',
    requests_in_progress: 'Заявки в работе',
    active_suppliers: 'Активные поставщики',
    active_agents: 'Активные агенты',
    all_tenders: 'Все тендеры',
    search: 'Поиск...',
    create_tender: 'Создать тендер',
    tender_title: 'Название тендера',
    client_name: 'Клиент',
    nmck: 'НМЦК',
    deadline: 'Срок подачи',
    status: 'Статус',
    status_ACTIVE: 'Активен',
    status_INACTIVE: 'Неактивен',
    status_LEAD: 'Лид',
    status_DRAFT: 'Черновик',
    status_SUBMITTED: 'Отправлена',
    status_IN_PROGRESS: 'В работе',
    status_REJECTED: 'Отклонена',
    status_COMPLETED: 'Завершена',
    status_VETTING: 'Проверка',
    status_IDLE: 'Ожидание',
    status_PROCESSING: 'В процессе',
    add_supplier: 'Добавить поставщика',
    available_agents: 'Доступные агенты',
    create_agent: 'Создать агента',
    description: 'Описание',
    provider: 'Провайдер',
    pending_actions: 'Ожидающие действия',
    all_client_requests: 'Все заявки клиентов',
    companies: 'Компании',
    tender_description: 'Описание тендера',
    received_at: 'Получено',
    process_request: 'Обработка заявки',
    profile: 'Профиль',
    save_changes: 'Сохранить изменения',
    notifications: 'Уведомления',
    email_notifications: 'Email уведомления',
    network_and_proxies: 'Сеть и прокси',
    enable_global_proxy: 'Включить глобальный прокси',
    platform_credentials: 'Учетные данные платформ',
    platform_name: 'Название платформы',
    login: 'Логин',
    password: 'Пароль',
    add_platform: 'Добавить платформу',
    select_client_to_impersonate: 'Выберите клиента для имперсонализации',
    all_clients: 'Все клиенты',
    add_client: 'Добавить клиента',
    client_dashboard: 'Панель клиента',
    my_companies: 'Мои компании',
    my_requests: 'Мои заявки',
    client_finances: 'Финансы',
    new_request: 'Новая заявка',
    total_requests: 'Всего заявок',
    in_progress: 'В процессе',
    completed: 'Завершено',
    date: 'Дата',
    submit_new_request: 'Отправить новую заявку',
    choose_company: 'Выберите компанию',
    tender_link: 'Ссылка на тендер',
    optional: 'необязательно',
    request_description_placeholder: 'Опишите тендер, укажите требования или просто вставьте текст из документации...',
    attach_files: 'Прикрепить файлы',
    save_draft: 'Сохранить черновик',
    submit_request: 'Отправить заявку',
    current_balance: 'Текущий баланс',
    download_documents: 'Скачать документы',
    completion_certificate: 'Акт выполненных работ',
    reconciliation_statement: 'Акт сверки',
    transactions_history: 'История транзакций',
    amount: 'Сумма',
    full_name: 'ФИО',
    email: 'Email',
    roles: 'Роли',
    new_employee: 'Новый сотрудник',
    add_employee: 'Добавить сотрудника',
    cancel: 'Отмена',
    new_client_creation: 'Создание нового клиента',
    client_name_placeholder: 'ООО "Ромашка"',
    contact_person_name: 'Контактное лицо (ФИО)',
    contact_person_email: 'Контактный email',
    client_created_successfully: 'Клиент успешно создан',
    generated_password_instruction: 'Сохраните и передайте клиенту сгенерированный пароль для входа.',
    credit_funds: 'Пополнить баланс',
    debit_funds: 'Списать средства',
    refund: 'Возврат',
    create_act: 'Сформировать акт',
    create_contract: 'Сформировать договор',
    initial_max_price: 'НМЦК',
    application_deadline: 'Срок подачи',
    tender_information: 'Информация о тендере',
    tender_items: 'Позиции тендера',
    quantity: 'Количество',
    unit: 'Ед. изм.',
    suggested_suppliers: 'Предложенные поставщики',
    run_supplier_scout: 'Найти поставщиков',
    bids_received: 'Полученные предложения',
    run_price_optimizer: 'Рассчитать цену',
    document_generation: 'Генерация документов',
    generate_documents: 'Сгенерировать документы',
    agent_settings: 'Настройки агента',
    back_to_agents: 'К списку агентов',
    system_prompt: 'Системный промпт',
    prompt_placeholder: 'Опишите роль и задачу агента...',
    model: 'Модель',
    proxy_settings: 'Настройки прокси',
    enable_proxy: 'Включить прокси',
    proxy_address: 'Адрес прокси',
    port: 'Порт',
    back_to_clients: 'К списку клиентов',
    finances_and_model: 'Финансы и модель',
    templates: 'Шаблоны',
    integrations: 'Интеграции',
    work_model: 'Модель работы',
    package_model: 'Пакетная',
    result_oriented_model: 'По результату',
    model_settings: 'Настройки модели',
    package_name: 'Название пакета',
    tender_count: 'Кол-во тендеров',
    package_cost: 'Стоимость пакета',
    tenders_remaining: 'Осталось тендеров',
    base_calculation_fee: 'Базовая плата',
    success_bonus_percentage: '% бонуса за успех',
    add_transaction: 'Добавить транзакцию',
    credit_balance: 'Пополнить баланс',
    add_company: 'Добавить компанию',
    add_template: 'Добавить шаблон',
    messenger_integrations: 'Интеграции',
    telegram_bot_token: 'Токен Telegram бота',
    company_not_found: 'Компания не найдена',
    back_to_companies: 'Назад к компаниям',
    company_details: 'Детали компании',
    company_name: 'Название компании',
    inn: 'ИНН',
    kpp: 'КПП',
    client_not_found: 'Клиент не найден',
    no_companies_added: 'Компании еще не добавлены.',
    new_document: 'Новый документ',
    new_operation: 'Новая операция',
    select_client: 'Выберите клиента',
    document_type: 'Тип документа',
    create_reconciliation: 'Акт сверки',
    generate: 'Сгенерировать',
    create_operation: 'Создать операцию',
    financial_documents: 'Финансовые документы',
    created_at: 'Дата создания',
    
    // Company Wizard
    add_new_company: 'Добавить новую компанию',
    edit_company: 'Редактирование компании',
    step_1_title: 'Шаг 1: Основная информация',
    step_2_title: 'Шаг 2: Подключение платформ',
    step_3_title: 'Шаг 3: Каналы коммуникации',
    step_4_title: 'Шаг 4: Проверка и сохранение',
    next_step: 'Далее',
    back_step: 'Назад',
    save: 'Сохранить',
    update_company: 'Обновить компанию',
    communication_settings: 'Настройки коммуникаций',
    default_rfq_email: 'Email для отправки запросов',
    review_and_save: 'Проверка и сохранение',
    basic_information: 'Основная информация',
    deactivate_company: 'Деактивировать',
    delete_company: 'Удалить компанию',
    deactivate_confirm_title: 'Вы уверены?',
    deactivate_confirm_text: 'Компания будет помечена как неактивная, но не будет удалена.',
    delete_confirm_title: 'Удалить компанию?',
    delete_confirm_text: 'Это действие необратимо. Вся связанная информация будет удалена.',
    confirm_delete: 'Да, удалить',
    confirm_deactivate: 'Да, деактивировать',
    company_successfully_added: 'Компания успешно добавлена!',
    company_successfully_updated: 'Компания успешно обновлена!',
    connected_platforms: 'Подключенные платформы',
    platform_url: 'URL платформы',
    connect: 'Подключить',
    disconnect: 'Отключить',
    connection_process: 'Процесс подключения',
    connection_instruction: 'Сейчас в новой вкладке откроется страница входа на платформу. После успешной авторизации вернитесь сюда и подтвердите подключение.',
    confirm_connection: 'Я авторизовался, подтвердить',
    connected: 'Подключено',
    not_connected: 'Не подключено',
    communication_channels: 'Каналы коммуникаций',
    connect_telegram: 'Подключить Telegram',
    connect_whatsapp: 'Подключить WhatsApp',
    scan_qr_code: 'Отсканируйте QR-код',
    scan_qr_instruction_telegram: 'Откройте Telegram, перейдите в Настройки > Устройства и отсканируйте этот QR-код, чтобы подключить сессию.',
    scan_qr_instruction_whatsapp: 'Откройте WhatsApp, перейдите в Меню > Связанные устройства и отсканируйте этот QR-код.',
    confirm_scan: 'Я отсканировал код',
    search_platform: 'Поиск по площадкам...',
    select_from_list: 'Выберите из списка',


  },
  en: {
    dashboard: 'Dashboard',
    tenders: 'Tenders',
    client_requests: 'Client Requests',
    clients: 'Clients',
    suppliers: 'Suppliers',
    finances: 'Finances',
    agents: 'Agents',
    employees: 'Employees',
    approvals: 'Approvals',
    audit_log: 'Audit Log',
    settings: 'Settings',
    Admin: 'Admin',
    Manager: 'Manager',
    Analyst: 'Analyst',
    Developer: 'Developer',
    Client: 'Client',
    active_requests: 'Active Requests',
    active_clients: 'Active Clients',
    new_requests: 'New Requests',
    requests_in_progress: 'Requests in Progress',
    active_suppliers: 'Active Suppliers',
    active_agents: 'Active Agents',
    all_tenders: 'All Tenders',
    search: 'Search...',
    create_tender: 'Create Tender',
    tender_title: 'Tender Title',
    client_name: 'Client Name',
    nmck: 'Initial Max Price',
    deadline: 'Deadline',
    status: 'Status',
    status_ACTIVE: 'Active',
    status_INACTIVE: 'Inactive',
    status_LEAD: 'Lead',
    status_DRAFT: 'Draft',
    status_SUBMITTED: 'Submitted',
    status_IN_PROGRESS: 'In Progress',
    status_REJECTED: 'Rejected',
    status_COMPLETED: 'Completed',
    status_VETTING: 'Vetting',
    status_IDLE: 'Idle',
    status_PROCESSING: 'Processing',
    add_supplier: 'Add Supplier',
    available_agents: 'Available Agents',
    create_agent: 'Create Agent',
    description: 'Description',
    provider: 'Provider',
    pending_actions: 'Pending Actions',
    all_client_requests: 'All Client Requests',
    companies: 'Companies',
    tender_description: 'Tender Description',
    received_at: 'Received At',
    process_request: 'Process Request',
    profile: 'Profile',
    save_changes: 'Save Changes',
    notifications: 'Notifications',
    email_notifications: 'Email Notifications',
    network_and_proxies: 'Network & Proxies',
    enable_global_proxy: 'Enable Global Proxy',
    platform_credentials: 'Platform Credentials',
    platform_name: 'Platform Name',
    login: 'Login',
    password: 'Password',
    add_platform: 'Add Platform',
    select_client_to_impersonate: 'Select Client to Impersonate',
    all_clients: 'All Clients',
    add_client: 'Add Client',
    client_dashboard: 'Client Dashboard',
    my_companies: 'My Companies',
    my_requests: 'My Requests',
    client_finances: 'Finances',
    new_request: 'New Request',
    total_requests: 'Total Requests',
    in_progress: 'In Progress',
    completed: 'Completed',
    date: 'Date',
    submit_new_request: 'Submit New Request',
    choose_company: 'Choose Company',
    tender_link: 'Tender Link',
    optional: 'optional',
    request_description_placeholder: 'Describe the tender, specify requirements, or just paste the text from the documentation...',
    attach_files: 'Attach Files',
    save_draft: 'Save Draft',
    submit_request: 'Submit Request',
    current_balance: 'Current Balance',
    download_documents: 'Download Documents',
    completion_certificate: 'Certificate of Completion',
    reconciliation_statement: 'Reconciliation Statement',
    transactions_history: 'Transactions History',
    amount: 'Amount',
    full_name: 'Full Name',
    email: 'Email',
    roles: 'Roles',
    new_employee: 'New Employee',
    add_employee: 'Add Employee',
    cancel: 'Cancel',
    new_client_creation: 'New Client Creation',
    client_name_placeholder: 'LLC "Daisy"',
    contact_person_name: 'Contact Person (Full Name)',
    contact_person_email: 'Contact Email',
    client_created_successfully: 'Client Created Successfully',
    generated_password_instruction: 'Please save and share the generated password with the client for them to log in.',
    credit_funds: 'Credit Funds',
    debit_funds: 'Debit Funds',
    refund: 'Refund',
    create_act: 'Create Act',
    create_contract: 'Create Contract',
    initial_max_price: 'Initial Max Price',
    application_deadline: 'Application Deadline',
    tender_information: 'Tender Information',
    tender_items: 'Tender Items',
    quantity: 'Quantity',
    unit: 'Unit',
    suggested_suppliers: 'Suggested Suppliers',
    run_supplier_scout: 'Run Supplier Scout',
    bids_received: 'Bids Received',
    run_price_optimizer: 'Run Price Optimizer',
    document_generation: 'Document Generation',
    generate_documents: 'Generate Documents',
    agent_settings: 'Agent Settings',
    back_to_agents: 'Back to Agents',
    system_prompt: 'System Prompt',
    prompt_placeholder: 'Describe the agent\'s role and task...',
    model: 'Model',
    proxy_settings: 'Proxy Settings',
    enable_proxy: 'Enable Proxy',
    proxy_address: 'Proxy Address',
    port: 'Port',
    back_to_clients: 'Back to Clients',
    finances_and_model: 'Finances & Model',
    templates: 'Templates',
    integrations: 'Integrations',
    work_model: 'Work Model',
    package_model: 'Package',
    result_oriented_model: 'Result-Oriented',
    model_settings: 'Model Settings',
    package_name: 'Package Name',
    tender_count: 'Tender Count',
    package_cost: 'Package Cost',
    tenders_remaining: 'Tenders Remaining',
    base_calculation_fee: 'Base Calculation Fee',
    success_bonus_percentage: 'Success Bonus %',
    add_transaction: 'Add Transaction',
    credit_balance: 'Credit Balance',
    add_company: 'Add Company',
    add_template: 'Add Template',
    messenger_integrations: 'Messenger Integrations',
    telegram_bot_token: 'Telegram Bot Token',
    company_not_found: 'Company not found',
    back_to_companies: 'Back to companies',
    company_details: 'Company Details',
    company_name: 'Company Name',
    inn: 'INN',
    kpp: 'KPP',
    client_not_found: 'Client not found',
    no_companies_added: 'No companies have been added yet.',
    new_document: 'New Document',
    new_operation: 'New Operation',
    select_client: 'Select Client',
    document_type: 'Document Type',
    create_reconciliation: 'Reconciliation Statement',
    generate: 'Generate',
    create_operation: 'Create Operation',
    financial_documents: 'Financial Documents',
    created_at: 'Created At',

    // Company Wizard
    add_new_company: 'Add New Company',
    edit_company: 'Edit Company',
    step_1_title: 'Step 1: Basic Information',
    step_2_title: 'Step 2: Connect Platforms',
    step_3_title: 'Step 3: Communication Channels',
    step_4_title: 'Step 4: Review and Save',
    next_step: 'Next',
    back_step: 'Back',
    save: 'Save',
    update_company: 'Update Company',
    communication_settings: 'Communication Settings',
    default_rfq_email: 'Default RFQ Email',
    review_and_save: 'Review and Save',
    basic_information: 'Basic Information',
    deactivate_company: 'Deactivate',
    delete_company: 'Delete Company',
    deactivate_confirm_title: 'Are you sure?',
    deactivate_confirm_text: 'The company will be marked as inactive but not deleted.',
    delete_confirm_title: 'Delete Company?',
    delete_confirm_text: 'This action cannot be undone. All related information will be removed.',
    confirm_delete: 'Yes, delete',
    confirm_deactivate: 'Yes, deactivate',
    company_successfully_added: 'Company added successfully!',
    company_successfully_updated: 'Company updated successfully!',
    connected_platforms: 'Connected Platforms',
    platform_url: 'Platform URL',
    connect: 'Connect',
    disconnect: 'Disconnect',
    connection_process: 'Connection Process',
    connection_instruction: 'A new tab will now open for you to log in to the platform. After successful authorization, return here and confirm the connection.',
    confirm_connection: 'I have logged in, confirm',
    connected: 'Connected',
    not_connected: 'Not Connected',
    communication_channels: 'Communication Channels',
    connect_telegram: 'Connect Telegram',
    connect_whatsapp: 'Connect WhatsApp',
    scan_qr_code: 'Scan QR Code',
    scan_qr_instruction_telegram: 'Open Telegram, go to Settings > Devices and scan this QR code to connect the session.',
    scan_qr_instruction_whatsapp: 'Open WhatsApp, go to Menu > Linked devices and scan this QR code.',
    confirm_scan: 'I have scanned the code',
    search_platform: 'Search platforms...',
    select_from_list: 'Select from list',
  },
};

export const LocalizationProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const t = useCallback((key: string): string => {
    return translations[language][key] || key;
  }, [language]);

  return (
    <LocalizationContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LocalizationContext.Provider>
  );
};